### ISSUE TITLE
Number should Autoincrement by default 

### ISSUE THREAD

**Issue by shridk** [ServiceNowNextExperience/hacktoberfest22-recipes#41]
In the Recipes table.  RCP0001001 Number should Auto increment by default when we add New Recipe. When new record is inserted in the Recipes table, Number filed should auto increment to total number of rows + 1. It is not working as expected currently..

When I added new Recipe I Got Number as RCP0001001 which is incorrect..

**Comment by briangodfreydev** [comment]
Looks like this may have been fixed.

**Comment by mjonssonme** [comment]
Looking in to this

**Comment by mjonssonme** [comment]
Actually, this might not fix it at all given the way recipes are loaded, it might change the number the new recipes get but they still won't be unique.

Do the recipes even need a number?

**Comment by shridk** [comment]
Yes Numbers are important not to display but for maintenance purpose.. Some one can just pull all the recipes and give unique numbers and push it back.. So that Each one has unique number and the new recipe should also get unique number..
